[package]
name = "sandbox00"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "*"
tokio = { version = "*", features = ["rt", "rt-multi-thread", "macros", "signal"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
schemars = "*"